export const categories = [
  "Alimentação",
  "Supermercado",
  "Restaurantes",
  "Delivery",
  "Transporte",
  "Combustível",
  "Transporte por app",
  "Manutenção de veículo",
  "Moradia",
  "Aluguel",
  "Energia elétrica",
  "Água",
  "Internet",
  "Condomínio",
  "Lazer",
  "Streaming",
  "Viagem",
  "Educação",
  "Saúde",
  "Medicamentos",
  "Pets",
  "Roupas",
  "Trabalho",
  "Investimentos",
  "Impostos",
  "Outros",
];
